### ISSUE TITLE
python 3.6 and Pyhive

### ISSUE THREAD

**Issue by denchik20071992** [dropbox/PyHive#156]
We are using Python 3.6.1 |Anaconda 4.4.0 (64-bit) build
Installed https://anaconda.org/anaconda/pyhive via conda

`import pyhive` worked well, but when I created connection 

```
 conn = hive.Connection(host="host"
                       , port=1000
                       , auth="KERBEROS"
                       , database="db"
                       , kerberos_service_name="hive"
                      )
```

the error occurs:

```
 /home/user/anaconda3/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py in readI32(self)
    215 
    216     def readI32(self):
--> 217         buff = self.trans.readAll(4)
    218         val, = unpack('!i', buff)
    219         return val
AttributeError: 'TSaslClientTransport' object has no attribute 'readAll'
```

in fact, the same code works well with python 2.7.

**Comment by jingw** [comment]
Dupe of #151
