### ISSUE TITLE
PyHive 0.3.0 fails on Python 3.6.1

### ISSUE THREAD

**Issue by myeyre** [dropbox/PyHive#113]
```Traceback (most recent call last):
  File "./test2.py", line 8, in <module>
    cursor = hive.connect(host='host',port=10010,username='hive').cursor()
  File "/path/to/python-3.6/lib/python3.6/site-packages/pyhive/hive.py", line 65, in connect
    return Connection(*args, **kwargs)
  File "/path/to/python-3.6/lib/python3.6/site-packages/pyhive/hive.py", line 136, in __init__
    response = self._client.OpenSession(open_session_req)
  File "/path/to/python-3.6/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 187, in OpenSession
    return self.recv_OpenSession()
  File "/path/to/python-3.6/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 199, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/path/to/python-3.6/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/path/to/python-3.6/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
AttributeError: 'TSaslClientTransport' object has no attribute 'readAll'
```
Same code works on Python 2.7, any ideas?

PyHive installed using pip: 
PyHive (0.3.0)
thrift (0.10.0)
thrift-sasl (0.2.1)

**Comment by myeyre** [comment]
reinstalled https://github.com/dropbox/PyHive/blob/master/dev_requirements.txt

**Comment by myeyre** [comment]
Reinstalled thrift-sasl from master branch and it works.

check:
https://github.com/dropbox/PyHive/blob/master/dev_requirements.txt

**Comment by ShawnDong72** [comment]
You make thrift-sasl update to the 0.3.0, this problem will be solved.
